// Problem 12  - Highly divisible triangular number.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

int GetFactors(int n) {
    int factors = 0;
    
    for (size_t i = 1; i <= sqrt(n); i++)
    {
        if (n % i == 0) {
            factors++;            
        }          
    }
    //ha negyzetszam akkor a negyzetgyokot mint osztot 2 szer szamoltuk bele
    if (sqrt(n) == 0)
        return 2 * factors - 1;
    else 
        return 2*factors;
}



int main()
{
    int range = 40;
    int divisors = 500;
    int tri_incr = 1;
    bool isFound = false;
   // int i = 1;
/*
    while(!isFound)
    {
        if (GetFactors(i) > divisors) {
            std::cout << i << std::endl;
            isFound = true;
        }
        tri_incr++;
        i = i + tri_incr;
    }
    */
    for (size_t i = 1; !isFound;)
    {
        if (GetFactors(i) > divisors) {
            std::cout << i << std::endl;
            isFound = true;
        }
        tri_incr++;
        i = i + tri_incr;
    }
}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
